version: 1.2
workflows:
   - subclass: cwl
     primaryDescriptorPath: /Dockstorew.cwl
     testParameterFiles:
         - /test/dockstore.cwl.json
         - /test/doesnotexist.txt
     name: foobar1
